debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
  [entryPoints.traefik]
  address = ":8080"
    [entryPoints.traefik.auth]
      [entryPoints.traefik.auth.basic]
        # Default: admin:admin - !!! Do not forget to change on production environment
        users = [
          "admin:$apr1$.BV/DrZn$KAYFPdAaaxgvJMFxLcfDh/"
        ]

[retry]

[api]
  entryPoint = "traefik"

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "mixology.ge"
  watch = true
  exposedbydefault = false

[acme]
  email = "info@mixology.ge"
  storage = "acme.json"
  entryPoint = "https"
  onHostRule = true
  # caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
  [acme.dnsChallenge]
    provider = "digitalocean"
    delayBeforeCheck = 0
    [[acme.domains]]
      main = "*.mixology.ge"
      sans = ["mixology.ge"]
  # [acme.httpChallenge]
    # entryPoint = "http"